version: '3.8'
services:
  fastapi:
    image: ${IMAGE_NAME}:${TAG}
    volumes:
      - ./server/:/app/server/ # Mount the source code directory into the container
    build:
      context: .
      dockerfile: fastapi_server/Dockerfile
      args:
        - LOCAL_ARCH=${LOCAL_ARCH}
    ports:
      - "${PORT}:${PORT}"
      - "11434:11434"
    environment:
      - PORT=${PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - QDRANT_API_URL=${QDRANT_API_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
